server:
   port: 8011

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis配置文件所在路径
   type-aliases-package: com.web.entity             #所有Entity别名类所在包
   mapper-locations: mybatis/mapper/**/*.xml        #mapper映射文件

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wisdomcity?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hx2020651423
    driver-class-name: com.mysql.jdbc.Driver
 
