server:
   port: 8020

mybatis:
   config-location: classpath:mapper/sdkServiceMapper-config.xml       #mybatis配置文件所在路径
   type-aliases-package: com.listen.model             #所有Entity别名类所在包
   mapper-locations: mapper/sdkservice/**/*.xml        #mapper映射文件

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdk_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hx2020651423
    driver-class-name: com.mysql.jdbc.Driver
 
